on:
  push:
    branches: master

name: Render site

jobs:
  render:
    name: Render site
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install bookdown
        run: Rscript -e 'install.packages("bookdown")'
      - name: Render site
        run: Rscript -e 'bookdown::render_book("index.Rmd")'
      - name: Commit results
        run: |
          git commit docs -m 'Re-build site' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
